PICO_UNIQUE_ID = "REDACTED_PICO_ID"
PICO_COM_PORT = "/dev/ttyACM0"

ADC_CHANNEL = 0
PIN_ANSWER = 2
PIN_DOOR = 3
PIN_MOSFET_TEST = 14

WINDOW_SIZE = 5
DEBOUNCE_COUNT = 3

THR_RING_VARIANCE = 300
THR_ANSWERED = 1800
THR_STABILITY = 100
THR_DOOR_OPEN = 2700
THR_DOOR_CLOSE = 2400
THR_IDLE = 800

RING_TIMEOUT_SEC = 30

TELEGRAM_TOKEN = "REDACTED_TELEGRAM_TOKEN"
TELEGRAM_CHAT_ID = REDACTED_CHAT_ID

PULSEAUDIO_USB_SINK = "alsa_output.usb-sound_card"
PULSEAUDIO_USB_SOURCE = "alsa_input.usb-sound_card"
PULSEAUDIO_PC_SINK = "alsa_output.pci-sound_card"
PULSEAUDIO_PC_SOURCE = "alsa_input.pci-sound_card"
